Repository chingu-voyages/v52-tier3-team-34, pull requests merged in 2024-12, with the labels that each got.

#87 Add Event and Venue Management Features with Filtering, Sorting, and Pagination
  client/src/api/events.ts
  client/src/api/health.ts
  client/src/api/venues.ts
  client/src/assets/Logo-with-text.svg
  client/src/components/EventCard.tsx
  client/src/components/Navbar.tsx
  client/src/components/VenueCard.tsx
  client/src/hooks/useEvents.ts
  client/src/hooks/useHealth.ts
  client/src/pages/AddEvent.tsx
  client/src/pages/AddVenue.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Home.tsx
  client/src/routes/__root.tsx
  client/src/routes/_protect/dashboard/index.tsx
  client/src/routes/_protect/dashboard/register-venue.tsx
  client/src/routes/index.tsx
  client/src/types/events.ts
  client/src/types/health.ts
  client/src/types/venues.ts
  client/src/validations/eventValidation.ts
  client/src/validations/venueValidation.ts
Labels: fe

#95 feat: enhance dashboard and event management with new components, routes, and messaging
  client/src/api/events.ts
  client/src/api/venues.ts
  client/src/components/EventCard.tsx
  client/src/components/Navbar.tsx
  client/src/components/VenueCard.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/EventDetails.tsx
  client/src/pages/Home.tsx
  client/src/pages/VenueDetails.tsx
  client/src/routeTree.gen.ts
  client/src/routes/__root.tsx
  client/src/routes/_protect/dashboard/event.$eventId.tsx
  client/src/routes/_protect/dashboard/venue.$venueId.tsx
  client/src/routes/login.tsx
  client/src/types/events.ts
  client/src/types/venues.ts
Labels: fe

#98 feat(dashboard): implement pagination and fetch user events by user ID
  client/src/api/userEvents.ts
  client/src/hooks/useUserEvents.ts
  client/src/pages/Dashboard.tsx
  client/src/types/userEvents.ts
Labels: fe

#97 feat(client): update app metadata and add favicon
  client/favicon.svg
  client/index.html
Labels: fe

#101 Refactor Codebase for Improved Consistency, Maintainability, and Typing
  client/eslint.config.js
  client/package-lock.json
  client/package.json
  client/src/api/events.ts
  client/src/api/health.ts
  client/src/api/userEvents.ts
  client/src/api/users.ts
  client/src/api/venues.ts
  client/src/components/EventCard.tsx
  client/src/components/Navbar.tsx
  client/src/components/VenueCard.tsx
  client/src/hooks/useEvents.ts
  client/src/hooks/useHealth.ts
  client/src/hooks/useUserEvents.ts
  client/src/hooks/useUsers.ts
  client/src/hooks/useVenues.ts
  client/src/hooks/useZones.ts
  client/src/main.tsx
  client/src/pages/AddEvent.tsx
  client/src/pages/AddVenue.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/EventDetails.tsx
  client/src/pages/Home.tsx
  client/src/pages/VenueDetails.tsx
  client/src/routes/__root.tsx
  client/src/routes/_protect.tsx
  client/src/routes/_protect/dashboard/add-event.tsx
  client/src/routes/_protect/dashboard/event.$eventId.tsx
  client/src/routes/_protect/dashboard/index.tsx
  client/src/routes/_protect/dashboard/register-venue.tsx
  client/src/routes/_protect/dashboard/venue.$venueId.tsx
  client/src/routes/login.tsx
  client/src/routes/privacy-policy.tsx
  client/src/routes/register.tsx
  client/src/types/venues.ts
  client/src/utils.ts
  client/src/validations/eventValidation.ts
  client/tailwind.config.js
  client/vite.config.ts
Labels: fe

#102 Integrate Venue Deletion Workflow with Confirmation Modal and API Integration
  client/src/api/venues.ts
  client/src/components/ConfirmationModal.tsx
  client/src/components/VenueCard.tsx
  client/src/hooks/useDeleteVenue.ts
Labels: fe

#107 Enhance Client and Server Configuration, Refactor Components, and Add Auth Dependencies
  client/package.json
  client/src/api/zones.ts
  client/src/components/ButtonGroup.tsx
  client/src/routes/map.tsx
  server/package-lock.json
  server/package.json
  server/src/config/env.ts
Labels: fe, be

#112 Enhance Map Usability with City Selection, Refined Interfaces, and Smooth Animations
  client/package-lock.json
  client/package.json
  client/src/pages/Home.tsx
  client/src/routes/map.tsx
  client/src/types/city.ts
  client/src/types/zones.ts
  client/src/utils.ts
Labels: fe

#113 add images and finish readme file on sprint 6
  LiveMusicFinderBanner.webp
  README.md
Labels: documentation

#116 Fix (FE): Resolve Venue Display and Map Flicker Issues on Initial Load
  client/src/config.ts
  client/src/routes/map.tsx
Labels: fe

#117 feat(event-form): complete user-specific event form with improved usability
  client/src/api/events.ts
  client/src/pages/AddEvent.tsx
  client/src/pages/AddVenue.tsx
  client/src/pages/Dashboard.tsx
  client/src/validations/eventValidation.ts
  client/src/validations/venueValidation.ts
Labels: fe
